[tool.poetry]
name = "package"
version = "0.1.0"
description = ""
authors = ["Ashley Bamber <bambera74@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pendulum = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
